module.exports = {
  "14-3-rantapohja-uuden-oulun-kasvaneet-voimavarat-ovat-olleet-hyodyksi-alueellemme": ["political"],
  "541": ["political"],
  "asukasvaikuttaminen-koetaan-puutteelliseksi": ["political"],
  "digitaaliset-valineet-kouluissa-%e2%80%89joko-olisi-aika-tarjota-opettajille-riittavat-tiedot-ja-taidot-uusien-me": ["expert"],
  "etaopetuksen-laatuun-kiinnitettava-huomiota": ["expert"],
  "ihmistieteille-uudet-tilat-osallistavassa-suunnitteluprosessissa": ["expert"],
  "jaalin-urheilualueen-rakennustyot-on-aloitettava-vuonna-2013": ["political"],
  "jokirannan-koulun-tilanne-kestamaton-osa-oppilaista-oireilee-yha": ["political", "expert"],
  "kaannekohta-on-kulman-takana": ["political"],
  "kaleva-kuusamontien-varren-asukkailla-on-oikeus-kunnallisiin-palveluihin": ["political"],
  "kaleva-mielipide-mihin-poliittiset-paatokset-perustuvat-ongelmaksi-esimerkiksi-oulun-kouluve": ["political"],
  "kaleva-uimahalli-ei-riita-tayttamaan-koillisen-suunnan-palvelutyhjiota": ["political"],
  "kalevan-yleisonosasto-lokakuu-2011-vastine-uutiseen-vasikkasuon-biokaasulaitos-etenee": ["political"],
  "kampuspohdintaa-kontinkankaan-kampusvalinta-joulukuu-2025": ["political", "expert"],
  "kayttojarjestelma-varsin-olematon-sivuseikka": ["political", "expert"],
  "keskustakampus-on-uhka-ict-sektorin-tulevaisuudelle": ["political", "expert"],
  "kierikin-sijainti-on-mahdollisuus-museo-voisi-toimia-myos-monipaikkaisena-osa-kierikissa-ja-osa-muu": ["political", "expert"],
  "kiiminki-ansaitsee-monitoimitalon-jokirannan-koulun-paikka-on-syke-talon-ja-lukion-laheisyydessa": ["political"],
  "koronan-vaikutukset-kuntalaisiin-arvioitava-arviointi-on-hyva-tehda-peilaten-oulun-tilannetta": ["political", "expert"],
  "kuntien-rooli-hyvinvoinnin-edistajana-ei-lakkaa-sote-rakenneuudistuksen-jalkeen": ["political"],
  "lahidemokratia-ja-tasa-arvotyo-ovat-keskiossa-uutta-peruskuntaa-rakennettaessa": ["political"],
  "linnanmaa-tarjoaa-merkittavia-kasautumisetuja-mita-lisaarvoa-paivittaistavara": ["political", "expert"],
  "luuppi-ansaitsee-kattavan-kokonaisratkaisun-sen-takaa-parhaiten-se-etta-asiat-kasitellaan-perin": ["political"],
  "mika-saa-asukkaan-sitoutumaan": ["political"],
  "mita-kuuluu-oulun-yhdyskuntalietteiden-kasittelylle": ["political"],
  "onko-meilla-oululaisilla-paattajilla-kykya-tarkastella-kokonaisuutta": ["political", "expert"],
  "opettajien-digihuoliin-tulee-vastata-koulutuksella-digitaaliset-valineet-eivat-ole-korvaamassa-opettajaa-painvastoin": ["expert"],
  "oulu-kaipaa-kipeasti-hankkeita-jotka-myos-toteutuvat-samalla-on-koko-kaupungin-etu-etta-kaupunkia-katsotaan-kokonaisuutena": ["political"],
  "oulu-takaisin-koulukaupunkien-joukkoon": ["political", "expert"],
  "oulun-kaupungintalo-on-jo-itsessaan-historiallinen-kohde-ja-soveltuu-paikallisen-historian-esit": ["political"],
  "oulun-normaalikoulu-ansaitsee-uudet-ja-terveet-tilat-lapset-heittopussina-kampussuunnitelmien-vuoksi": ["political", "expert"],
  "oulun-palveluverkko-ja-pedagogiikka-tyorauha-palautettava-kouluihin": ["political", "expert"],
  "oulun-yliopistokampus-toimiva-nykyisellaan-mika-on-se-malli-johon-visio-yliopistosta-keskustassa-perustuu": ["political", "expert"],
  "peramerenkaari-on-nostettava-asialistalle-paatoksenteossa-pohjois-suomi-ja-pohjois": ["political"],
  "pohjoismainen-malli-kuntaliitoksiin-vai-oulujoen-kaupunki": ["political"],
  "raksilaan-wow-kampus-kuntapaattajana-en-kykene-nakemaan-mista-loytyvat-tarvittavat-resurs": ["political", "expert"],
  "saastot-tulee-etsia-yhdessa-teatterin-toimivan-johdon-kanssa-jotta-ne-olisivat-toteutettavissa-ilman-etta-teatterin-toi": ["political"],
  "sahkoinen-perhekeskus-esimerkki-tulevaisuuden-digitaalisista-palveluista": ["political", "expert"],
  "sisailmaongemat-eivat-ole-vain-koulujen-riessa": ["political", "expert"],
  "toistuvia-rakenteita-valmisteluprosessin-ongelmat-kunnallishallinnossa-marraskuu-2025": ["political"],
  "vastuu-lapsen-ja-nuoren-suojelusta-ja-hyvinvoinnista-on-aina-aikuisella": ["political"],
  "yliopistoa-ja-ammattikorkeakoulua-yhdistettiin-kalliisti-yhteiskunta-on-investoinut-linnanmaan-kampukseen-kymmenia-miljoonia": ["political", "expert"],
  "yokirjan-synkkyydesta-kohti-kukoistavaa-kulttuuri-%e2%80%8boulua": ["political"]
};
