module.exports = {
  categories: {
    "politiikka-ja-paatoksenteko": {
      eyebrow: "Kategoria",
      lead: "Poliittiset puheenvuorot, valtuustoaloitteet, mielipidekirjoitukset, blogitekstit ja mediassa näkyneet sisällöt samassa näkymässä.",
      context: "Tämä kategoria näyttää, miten poliittinen työ on näkynyt sekä päätöksenteossa että julkisessa keskustelussa. Pääpaino on valtuustotyössä, mutta mukana ovat myös kirjoitukset ja esiintymiset, joissa samat teemat jatkuvat eri muodoissa.",
      primaryType: "council-speeches",
      primaryLabel: "Pääpaino",
      primaryText: "Valtuustopuheenvuorot muodostavat kategorian rungon. Niiden ympärille asettuvat valtuustoaloitteet, mielipiteet, blogitekstit ja mediassa näkyneet sisällöt.",
      highlightsTitle: "Sisällöt rooleittain",
      browseTitle: "Kaikki sisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa koko kategoriaa uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Aloita sisältötyypeistä, jos etsit tiettyä tekemisen muotoa. Toistuvat teemat auttavat löytämään saman keskustelun eri vuosilta ja eri rooleista.",
      backLabel: "Kaikki kategoriat"
    },
    "kaupunkikehitys-ja-palveluverkko": {
      eyebrow: "Kategoria",
      lead: "Kaupunkikehityksen, maankäytön, liikkumisen ja palveluverkon ratkaisut koottuna samaan näkymään.",
      context: "Tämä kategoria kokoaa sisällöt, joissa tarkastelen Oulun kasvua koko kaupungin arjen näkökulmasta. Mukana ovat palveluverkon muutokset, koulujen ja muiden palvelujen sijainti, maankäyttö, kaavoitus, liikkuminen sekä isot kaupunkirakenteen ratkaisut.",
      primaryType: "council-speeches",
      primaryLabel: "Pääpaino",
      primaryText: "Valtuustopuheenvuoroissa näkyy, miten palveluverkkoa ja kaupunkirakennetta on käsitelty päätöksenteon eri vaiheissa. Mielipidekirjoitukset ja blogitekstit avaavat samaa kokonaisuutta laajemmin: mitä vaikutuksia ratkaisuilla on asukkaiden arkeen, alueiden tasapuolisuuteen ja valmistelun laatuun.",
      highlightsTitle: "Kaupunkikehitys päätöksissä ja keskustelussa",
      browseTitle: "Kaikki kaupunkikehityksen sisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa kokonaisuutta uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Aloita valtuustopuheenvuoroista, jos haluat nähdä päätöksenteon vaiheet. Avainsanat, kuten palveluverkko, maankäyttö, Jääli, Raksila ja Linnanmaa, näyttävät miten samat kysymykset palaavat eri vuosina eri muodossa.",
      backLabel: "Kaikki kategoriat"
    },
    "sivistys-ja-koulutus": {
      eyebrow: "Kategoria",
      lead: "Sivistyksen, koulutuksen, varhaiskasvatuksen ja oppimisen palvelujen ratkaisut samassa näkymässä.",
      context: "Tämä kategoria kokoaa sisällöt, joissa tarkastelen sivistystä kaupungin pitkäjänteisenä perustana. Mukana ovat kouluverkko, varhaiskasvatus, oppimisen tuki, nuorten hyvinvointi, kulttuuri- ja taidekasvatus, korkeakoulutus sekä se, millaisella tiedolla näitä päätöksiä valmistellaan.",
      primaryType: "council-speeches",
      primaryLabel: "Pääpaino",
      primaryText: "Valtuustopuheenvuoroissa sivistys näkyy palveluverkon, talouden, tilojen, johtamisen ja yhdenvertaisuuden kysymyksinä. Kirjoitukset ja blogitekstit täydentävät kokonaisuutta avaamalla, miten päätökset vaikuttavat lapsiin, nuoriin, opiskelijoihin, perheisiin ja koko kaupungin osaamispohjaan.",
      highlightsTitle: "Sivistys päätöksissä ja arjessa",
      browseTitle: "Kaikki sivistyksen ja koulutuksen sisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa kokonaisuutta uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Valtuustopuheenvuorot näyttävät, miten sivistyspalveluista on päätetty valtuustossa. Avainsanat, kuten palveluverkko, kouluverkko, varhaiskasvatus, kampus ja hyvinvointi, auttavat seuraamaan samaa kysymystä eri vuosien keskusteluissa.",
      backLabel: "Kaikki kategoriat"
    },
    "yliopisto-ja-korkeakoulut": {
      eyebrow: "Kategoria",
      lead: "Yliopistoa, korkeakoulupolitiikkaa, kampusratkaisuja, avointa tiedettä ja korkeakouluopetusta koskevat sisällöt samassa näkymässä.",
      context: "Tämä kategoria kokoaa sisällöt, joissa yliopisto näkyy sekä työyhteisönä, yhteiskunnallisena instituutiona että kaupungin kehitykseen vaikuttavana toimijana. Mukana ovat kampus- ja tilaratkaisut, yliopistohallinto, avoin tiede, opettajankoulutus, tekoälylukutaito sekä mediahaastattelut, joissa korkeakoulutyö avautuu laajemmalle yleisölle.",
      primaryType: "media",
      primaryLabel: "Pääpaino",
      primaryText: "Mediassa näkyvät haastattelut ja uutiset muodostavat kategorian rungon. Niiden rinnalla mielipidekirjoitukset, puheenvuorot ja blogitekstit näyttävät, miten samat korkeakoulukysymykset ovat jatkuneet päätöksenteossa, työyhteisössä ja julkisessa keskustelussa.",
      highlightsTitle: "Korkeakoulu julkisessa keskustelussa",
      browseTitle: "Kaikki yliopisto- ja korkeakoulusisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa kokonaisuutta uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Kampus-, Linnanmaa- ja Raksila-avainsanat avaavat yliopiston suhdetta kaupunkiin. Avoin tiede, opettajankoulutus, tekoäly ja Generation AI näyttävät puolestaan, miten korkeakoulutyö näkyy opetuksessa, tutkimuksessa ja asiantuntijaroolissa.",
      backLabel: "Kaikki kategoriat"
    },
    "koulutusteknologia": {
      eyebrow: "Kategoria",
      lead: "Koulutusteknologian, digipedagogiikan, oppimisympäristöjen ja tekoälylukutaidon sisällöt samassa näkymässä.",
      context: "Tämä kategoria kokoaa sisällöt, joissa teknologiaa tarkastellaan opetuksen ja oppimisen rakenteena, ei irrallisena välineenä. Mukana ovat digipedagogiikka, mobiilioppiminen, oppimisympäristöt, avoimet materiaalit, opettajien osaaminen sekä tekoälyn käyttö koulussa ja korkeakouluopetuksessa.",
      primaryType: "media",
      primaryLabel: "Pääpaino",
      primaryText: "Mediahaastattelut ja asiantuntijatekstit muodostavat kategorian rungon. Niissä koulutusteknologia näkyy käytännön opetustyön, opettajankoulutuksen, tutkimuksen ja julkisen keskustelun risteyksessä.",
      highlightsTitle: "Teknologia opetuksen ja oppimisen rakenteena",
      browseTitle: "Kaikki koulutusteknologian sisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa kokonaisuutta uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Tekoäly, Generation AI, digipedagogiikka, mobiilioppiminen ja avoimet materiaalit näyttävät, miten sama kysymys on muuttunut vuosien aikana: milloin teknologia tukee ajattelua, yhteistä työskentelyä ja opettajan pedagogisia ratkaisuja.",
      backLabel: "Kaikki kategoriat"
    },
    "tekoaly": {
      eyebrow: "Kategoria",
      lead: "Tekoälyä, tekoälylukutaitoa, Generation AI -työtä, lausuntoja, esityksiä ja mediahaastatteluja samassa näkymässä.",
      context: "Tämä kategoria kokoaa sisällöt, joissa tekoälyä tarkastellaan opetuksen, oppimisen, yhteiskunnan ja asiantuntijatyön näkökulmasta. Mukana ovat koulutukset, keynote- ja paneeliesitykset, mediassa näkyneet haastattelut, lausunnot sekä Generation AI -hankkeen kautta syntyneet materiaalit.",
      primaryType: "media",
      primaryLabel: "Pääpaino",
      primaryText: "Mediahaastattelut muodostavat kategorian rungon, mutta esitykset ja lausunnot tekevät näkyväksi varsinaisen asiantuntijatyön. Kokonaisuus näyttää, miten tekoälystä on puhuttu yhtä aikaa koulujen arjessa, opettajankoulutuksessa, päätöksenteossa ja julkisessa keskustelussa.",
      highlightsTitle: "Tekoäly julkisessa asiantuntijatyössä",
      browseTitle: "Kaikki tekoälysisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa kokonaisuutta uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Tekoälylukutaito, Generation AI, koulut, opettajankoulutus, varhaiskasvatus ja digipedagogiikka näyttävät, missä yhteyksissä tekoälyä käsitellään: taitona, pedagogisena kysymyksenä, hallinnon lausuntoasiana ja yhteiskunnallisena muutoksena.",
      backLabel: "Kaikki kategoriat"
    },
    "opettajankoulutus": {
      eyebrow: "Kategoria",
      lead: "Opettajankoulutusta, täydennyskoulutusta, digipedagogiikkaa, tekoälylukutaitoa ja opettajan työn muutosta koskevat sisällöt samassa näkymässä.",
      context: "Tämä kategoria kokoaa sisällöt, joissa opettajankoulutus näkyy luentoina, koulutuksina, lausuntoina, mediahaastatteluina ja kirjoituksina. Mukana ovat opettajan osaaminen, pedagoginen suunnittelu, digitaaliset välineet, tekoälylukutaito, monilukutaito sekä se, miten koulutuksen muutoksia tuodaan opettajien arkeen.",
      primaryType: "presentations",
      primaryLabel: "Pääpaino",
      primaryText: "Esitykset ja videot muodostavat kategorian rungon, koska opettajankoulutuksen työ näkyy konkreettisesti luennoissa, VESO-koulutuksissa, paneeleissa ja avoimissa materiaaleissa. Lausuntojen ja mediahaastattelujen kautta sama osaaminen näkyy myös koulutuspolitiikassa ja julkisessa keskustelussa.",
      highlightsTitle: "Opettajankoulutus käytännön asiantuntijatyönä",
      browseTitle: "Kaikki opettajankoulutuksen sisällöt",
      browseLead: "Rajaa näkymää sisältötyypin mukaan tai selaa kokonaisuutta uusimmasta vanhimpaan.",
      relatedTitle: "Toistuvat teemat",
      guideTitle: "Miten tätä kannattaa lukea",
      guideText: "Tekoälylukutaito, digipedagogiikka, monilukutaito, VESO-koulutukset, Generation AI ja opettajan työn muutos näyttävät, miten opettajankoulutus yhdistää tutkimuksen, koulutukset, materiaalit ja yhteiskunnallisen asiantuntijatyön.",
      backLabel: "Kaikki kategoriat"
    }
  },
  defaultCategory: {
    eyebrow: "Kategoria",
    lead: "Tähän kategoriaan kootut sisällöt samasta aihepiiristä.",
    context: "Kategoriasivu kokoaa saman aihepiirin sisällöt yhteen: uusimmat näkyvät ensin, ja laajemman kokonaisuuden voi hahmottaa sisältötyyppien ja avainsanojen kautta.",
    primaryLabel: "Sisältöjä",
    primaryText: "Sivu kokoaa samaan aihepiiriin liittyvät kirjoitukset, puheenvuorot, julkaisut ja muut sisällöt.",
    highlightsTitle: "Sisältötyypit",
    browseTitle: "Sisällöt",
    browseLead: "Selaa sisältöjä uusimmasta vanhimpaan.",
    relatedTitle: "Läheiset avainsanat",
    guideTitle: "Miten tätä kannattaa lukea",
    guideText: "Uusimmat sisällöt näkyvät ensin. Sisältötyypit ja avainsanat auttavat hahmottamaan, millaisista teksteistä ja aiheista kategoria muodostuu.",
    backLabel: "Kaikki kategoriat"
  }
};
