module.exports = {
  blog: {
    "17": ["personal"],
    "aanesta-jari-laru-oulun-yliopiston-kollegioon": ["expert"],
    "asiaa-himmeleista-ja-aluehallinnosta": ["political"],
    "bensalenkkareista-ja-piraateista-miten-jaalin-nuorisoa-voisi-ottaa-paremmin-huomioon": ["political"],
    "berliinissa-uutena-vuotena-2007": ["personal"],
    "blogi-on-muuttanut-eika-ihan-naarmuitta": ["expert"],
    "etusivu": ["political"],
    "hyvaa-eurooppa-paivaa": ["political"],
    "jari-larulle-kansallinen-avoimen-tieteen-palkinto": ["expert"],
    "jari-larun-verkkolive": ["expert"],
    "kayppas-katsomassa-vastauksiani-vaalikoneissa": ["political"],
    "kehuttua-koulutusteknologian-perusopintojen-johdantoluento": ["expert"],
    "kaikki-lahtee-yksilosta-nobel-palkittu-martti-ahtisaari-radio-suomen-haastattelussa": ["political"],
    "kiiminki-kymmenen-parhaan-joukossa-lapsiystavallisyydessa-hienoa": ["political"],
    "kiiminki-osana-oulujoen-kaupunkia-visio-2021": ["political"],
    "kokoomus-esittaa-minua-sivistys-ja-kulttuurilautakunnan-jaseneksi": ["political"],
    "kommentoin-facebookissa-toivetta-saada-lisaresursseja-ennaltaehkaisevaan-tyohon-case-kauhajoki": ["political"],
    "kriisitalouden-pitka-hanta-case-ideapark-kiimingissa": ["political"],
    "ktk149-digiluokka": ["expert"],
    "ktk149-digiluokka-aanet": ["expert"],
    "kurkistus-sivustoni-tekniikkaan": ["expert"],
    "larux": ["expert"],
    "larun-laitenurkka-testaa-kandao-360-kokouskamerat": ["expert"],
    "liikkuva-oulu-voi-hyvin": ["political"],
    "lomamatkat": ["personal"],
    "mina-olen-annaaanilapselle-ehdokas": ["political"],
    "missa-mennaan-hyvinvointia-tukevissa-digipalveluissa": ["political", "expert"],
    "mista-on-hyva-kaupunginvaltuutettu-tehty": ["political"],
    "nizza-2018": ["personal"],
    "onko-koulu-lapsia-vai-opettajia-varten-lea-pulkkisen-lausuntojen-pohdiskelua": ["political", "expert"],
    "onko-nykymuotoinen-tohtorikoulutus-tiensa-paassa-siirretty": ["expert"],
    "olisikohan-oululla-mahdollista-paasta-vastaavaan-kukoistukseen-kuin-muinainen-paliputra-tai-miletos": ["personal"],
    "osallistun-tuleeko-kuntalainen-kuulluksi-paneeliin-14102008-kirkkotorin-koulutuskeskuksessa-oulussa": ["political"],
    "palveluverkko-2023-reunaehtojen-tarkastelua": ["political", "expert"],
    "pohjoismainen-malli-kuntaliitoksiin-vai-oulujoen-kaupunki-2": ["political"],
    "punaisenladonkankaan-kompostialue-vs-tutkimus-jonka-mukaan-madatys-on-kompostointia-ymparistoystavallisempaa": ["political"],
    "rantalakeus-249-ei-suur-oulu-vaan-laajempi-yhteinen-oulu": ["political"],
    "ratikalla-ruskoon-kutsutaksilla-kauppaan-vai-sahkoautolla-kirkolle": ["political"],
    "roadtrip-oulu-krakova-oulu": ["personal"],
    "roadtrip-oulu-skopje-oulu-vajaa-10-000km": ["personal"],
    "sain-kierikkia-koskevan-lisayksen-sikun-kayttosuunnitelmaan": ["political"],
    "seurakuntavaalit-tulevat-ja-ehdolla-ollaan-miksi-tallainen-agnostinen-liberaali-on-nailla-selkosilla-ehdokkaana": ["political"],
    "silloin-kun-sita-oltiin-larges-securityn-sysop-bbs-muisteluita": ["personal"],
    "sivistys-ja-kulttuurilautakunta-kokoontui-ouluhallissa-laajennus-ja-remontti-on-luvassa-tulevaisuudessa": ["political"],
    "te-muut-voisitte-menna-vaikka-kahville-vastine-pauli-maatan-kirjoitukseen-ihanseutuyhteistyosta": ["political"],
    "te-muut-voisitte-menna-vaikka-kahville-vastine-pauli-maatan-kirjoitukseen-ihanseutuyhteistyosta-2": ["political"],
    "tein-muutosesityksen-jokirannan-koulu-tulee-sijoittaa-puiravan-kolmioon": ["political"],
    "tunnelmia-lahidemokratiatoimikunnan-viimeisesta-kokouksesta": ["political"],
    "tvt-koulun-johtamisen-valineena-luento-mobiilioppiminen-mita-se-teknologia-tahtoo": ["expert"],
    "tyomatkapyorailijan-hammastelya": ["political"],
    "ulkoiset-rss-syotteet-kohdalleen": ["expert"],
    "vaalielaimet-ja-muu-grafiikka-vuoden-2017-vaaleissa": ["political"],
    "vaalinalustunnelmia": ["political"],
    "vote-jari-laru-to-oulu-university-collegium": ["expert"],
    "vuoden-2017-kuntavaalit": ["political"],
    "kuntavaalit-2017-best-of": ["political"],
    "vuorovaikutussuunnitelman-valmistelutyoryhman-kokous": ["political"],
    "yhdistysaktivisti-2": ["personal"]
  },
  publications: {
    "arjesta-energiaa-blogi-nykyaikainen-jatteidenkasittely-ei-hairitse-ihmista-eihan": ["political"],
    "kulttuurihyvinvointi-kuuluu-kaikille": ["political"],
    "ma-haluun-nayttaa-sulle-mun-skratsin": ["expert"],
    "matalan-kynnyksen-videot-osa-nykyaikaista-oppimisymparistoa": ["expert"],
    "milla-pelisaannoilla-ja-osaamisella-koulussa-operoidaan": ["expert"],
    "monilukutaitoa-keinoalya-ja-koodaamista-s2-opetuksessa": ["expert"],
    "paattajalta-keskustakampuksen-lammikossa-uiva-musta-joutsen-uhkaa-alueemme-ict-sektoria": ["political", "expert"],
    "virolaisen-opettajankoulutuksen-digi-ihmetta-aimistelemassa": ["expert"],
    "yhdessa-toisiamme-tukien-opetuksen-ja-oppimisen-pilvipalveluiden-kayttoonotto-ja-vertaistuen-eri-kanavat": ["expert"]
  }
};
